############################
## CHANGE THESE
############################

baseURL: "https://Lassenwirdas.github.io/Website"
title: Website

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
